name: MCP Contract Tests - UI Drift Protection

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'apps/web/src/**/*.tsx'
      - 'apps/web/src/**/*.ts'
      - 'apps/web/src/**/*.css'

jobs:
  mcp-contract-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.19.4'

    - name: Install dependencies
      working-directory: apps/web
      run: npm install

    - name: Install Playwright Browsers
      working-directory: apps/web
      run: npx playwright install

    - name: Build Application
      working-directory: apps/web
      run: npm run build

    - name: Start Application
      working-directory: apps/web
      run: |
        npm run preview &
        sleep 5

    - name: Run MCP Contract Tests
      working-directory: apps/web
      run: |
        echo "🔒 Running MCP UI Contract Tests..."
        npx playwright test tests/a11y-perf/ --reporter=html

    - name: Run Accessibility Audits
      working-directory: apps/web
      run: |
        echo "♿ Running Accessibility Contract Tests..."
        npx playwright test tests/a11y-perf/accessibility.spec.ts

    - name: Run Performance Contract Tests
      working-directory: apps/web
      run: |
        echo "⚡ Running Performance Contract Tests..."
        npx playwright test tests/a11y-perf/performance.spec.ts

    - name: Upload Test Reports
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: mcp-contract-test-results
        path: |
          apps/web/playwright-report/
          apps/web/test-results/

    - name: Comment PR on Contract Violations
      if: failure()
      uses: actions/github-script@v7
      with:
        script: |
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: '🚨 **MCP Contract Tests Failed** - UI drift detected or accessibility/performance thresholds violated. Check the test artifacts for details.'
          })