name: build-and-deploy

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: apps/web/package-lock.json

      - name: Install dependencies
        working-directory: apps/web
        run: npm ci

      - name: Run type checking
        working-directory: apps/web
        run: npm run typecheck

      - name: Run linting
        working-directory: apps/web
        run: echo "Skipping linting step temporarily" && exit 0

      - name: Build web app
        working-directory: apps/web
        run: npm run build

      - name: Upload artifact to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: pravado-app
          directory: apps/web/dist
          wranglerVersion: '3'
